-- MySQL Script generated by MySQL Workbench
-- 04/09/15 15:08:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CHAT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CHAT` ;

-- -----------------------------------------------------
-- Schema CHAT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CHAT` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CHAT` ;

-- -----------------------------------------------------
-- Table `CHAT`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHAT`.`Users` ;

CREATE TABLE IF NOT EXISTS `CHAT`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `state_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `CHAT`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHAT`.`Messages` ;

CREATE TABLE IF NOT EXISTS `CHAT`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_user_id` INT NULL,
  `recipient_user_id` INT NULL,
  `body` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `sender_user_id_idx` (`sender_user_id` ASC),
  INDEX `recipient_user_id_idx` (`recipient_user_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
